### ISSUE TITLE
Anymore devlopment on Hacker Pulp

### ISSUE THREAD

**Issue by GrooverMD** [BrianOtto/nasm-uefi#1]
Brain,

Are you going to post some more article on Hacker Pulp?

Regards,
Mark.

**Comment by GrooverMD** [comment]
[build.txt](https://github.com/BrianOtto/nasm-uefi/files/4304655/build.txt)

I've taking the liberty of modifying the build.bat file to be more user friendly. Just save the build.txt file and rename to .bat

**Comment by BrianOtto** [comment]
I was able to find the articles archived on an older laptop and they have been added to the [Wiki](https://github.com/BrianOtto/nasm-uefi/wiki) now.

I never completed the series and so there's only two articles unfortunately.

**Comment by GrooverMD** [comment]
I thought that was a very good series Brian, I was hoping you would do some more. Ahh well.
